"""Build the Aftermath panel and its sensoryESP remote adapter."""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist" / "aftermath.lua"
SOURCES = {
    "Config": ROOT / "src" / "Config.lua",
    "UI": ROOT / "src" / "Ui.lua",
    "Main": ROOT / "src" / "Main.lua",
    "SensoryESP": ROOT / "src" / "Integrations" / "SensoryESP.lua",
    "NeverLose": ROOT / "vendor" / "NeverLose.lua",
}


def build_bundle() -> str:
    chunks = []
    digest = hashlib.sha256()
    for name, path in SOURCES.items():
        source = path.read_text(encoding="utf-8")
        if not source.strip():
            raise ValueError(f"Empty source: {path}")
        digest.update(name.encode() + b"\0" + source.encode() + b"\0")
        chunks.append(
            f"local function Load{name}()\n"
            f"-- BEGIN {path.relative_to(ROOT).as_posix()}\n"
            f"{source.rstrip()}\n"
            f"-- END {path.relative_to(ROOT).as_posix()}\nend\n"
        )

    return (
        "-- Aftermath: independent panel with optional remote sensoryESP.\n"
        "-- Generated by scripts/build.py; edit src/ and rebuild.\n"
        "-- See LICENSE and THIRD_PARTY_NOTICES.md for attribution.\n"
        f"-- Source SHA-256: {digest.hexdigest()}\n\n"
        + "\n".join(chunks)
        + "\nreturn LoadMain().Start(LoadConfig(), LoadUI(), LoadNeverLose, LoadSensoryESP())\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify the existing bundle without writing.")
    args = parser.parse_args()
    bundle = build_bundle()
    if args.check:
        if not DIST.is_file() or DIST.read_text(encoding="utf-8") != bundle:
            print("FAIL: dist/aftermath.lua is missing or out of date.")
            return 1
        print(f"OK: bundle matches all {len(SOURCES)} local sources.")
        return 0
    DIST.parent.mkdir(parents=True, exist_ok=True)
    DIST.write_text(bundle, encoding="utf-8", newline="\n")
    print(f"Built {DIST.relative_to(ROOT)} ({DIST.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
